import type { Shortcut } from './types';

function mk(
  tool: string,
  level: number,
  description: string,
  expectedCombo: string[],
): Shortcut {
  return { id: crypto.randomUUID(), description, expectedCombo, tool, level };
}

export const INITIAL_SHORTCUTS: Shortcut[] = [
  // ── General ──
  mk('General', 1, 'Copiar texto seleccionado', ['Control', 'c']),
  mk('General', 1, 'Pegar contenido', ['Control', 'v']),
  mk('General', 1, 'Cortar selección', ['Control', 'x']),
  mk('General', 1, 'Guardar', ['Control', 's']),
  mk('General', 2, 'Deshacer última acción', ['Control', 'z']),
  mk('General', 2, 'Rehacer', ['Control', 'y']),
  mk('General', 2, 'Buscar texto', ['Control', 'f']),
  mk('General', 2, 'Seleccionar todo', ['Control', 'a']),
  mk('General', 2, 'Poner en negrita', ['Control', 'b']),
  mk('General', 3, 'Reemplazar texto', ['Control', 'h']),
  mk('General', 3, 'Imprimir', ['Control', 'p']),
  mk('General', 3, 'Ir al principio del documento', ['Control', 'Home']),
  mk('General', 3, 'Ir al final del documento', ['Control', 'End']),
  mk('General', 3, 'Guardar como', ['Control', 'Shift', 's']),
  mk('General', 4, 'Seleccionar desde el cursor hasta el inicio', ['Control', 'Shift', 'Home']),
  mk('General', 4, 'Seleccionar desde el cursor hasta el final', ['Control', 'Shift', 'End']),

  // ── VS Code ──
  mk('VS Code', 1, 'Guardar archivo', ['Control', 's']),
  mk('VS Code', 1, 'Copiar línea', ['Control', 'c']),
  mk('VS Code', 1, 'Cortar línea', ['Control', 'x']),
  mk('VS Code', 2, 'Abrir archivo rápidamente', ['Control', 'p']),
  mk('VS Code', 2, 'Comentar línea', ['Control', '/']),
  mk('VS Code', 2, 'Buscar en el archivo', ['Control', 'f']),
  mk('VS Code', 2, 'Reemplazar en el archivo', ['Control', 'h']),
  mk('VS Code', 2, 'Formatear documento', ['Shift', 'Alt', 'f']),
  mk('VS Code', 2, 'Renombrar símbolo', ['F2']),
  mk('VS Code', 3, 'Abrir la paleta de comandos', ['Control', 'Shift', 'p']),
  mk('VS Code', 3, 'Buscar en todo el proyecto', ['Control', 'Shift', 'f']),
  mk('VS Code', 3, 'Abrir la terminal integrada', ['Control', '`']),
  mk('VS Code', 3, 'Ir a una línea', ['Control', 'g']),
  mk('VS Code', 3, 'Abrir la configuración', ['Control', ',']),
  mk('VS Code', 4, 'Duplicar la línea hacia abajo', ['Shift', 'Alt', 'ArrowDown']),
  mk('VS Code', 4, 'Mover la línea hacia arriba', ['Alt', 'ArrowUp']),
  mk('VS Code', 4, 'Mover la línea hacia abajo', ['Alt', 'ArrowDown']),
  mk('VS Code', 4, 'Seleccionar la siguiente coincidencia', ['Control', 'd']),

  // ── Chrome ──
  mk('Chrome', 1, 'Abrir nueva pestaña', ['Control', 't']),
  mk('Chrome', 1, 'Cerrar pestaña actual', ['Control', 'w']),
  mk('Chrome', 1, 'Abrir nueva ventana', ['Control', 'n']),
  mk('Chrome', 2, 'Reabrir última pestaña cerrada', ['Control', 'Shift', 't']),
  mk('Chrome', 2, 'Ir a la barra de direcciones', ['Control', 'l']),
  mk('Chrome', 2, 'Recargar la página', ['Control', 'r']),
  mk('Chrome', 2, 'Buscar en la página', ['Control', 'f']),
  mk('Chrome', 2, 'Marcar como favorito', ['Control', 'd']),
  mk('Chrome', 3, 'Abrir modo incógnito', ['Control', 'Shift', 'n']),
  mk('Chrome', 3, 'Abrir el historial', ['Control', 'h']),
  mk('Chrome', 3, 'Abrir las descargas', ['Control', 'j']),
  mk('Chrome', 3, 'Ir a la pestaña siguiente', ['Control', 'Tab']),
  mk('Chrome', 3, 'Mostrar u ocultar la barra de favoritos', ['Control', 'Shift', 'b']),
  mk('Chrome', 4, 'Ir a la pestaña 5', ['Control', '5']),
  mk('Chrome', 4, 'Cerrar la ventana', ['Control', 'Shift', 'w']),
  mk('Chrome', 4, 'Abrir herramientas de desarrollo', ['Control', 'Shift', 'i']),

  // ── Word ── (atajos internacionales)
  mk('Word', 1, 'Poner en negrita', ['Control', 'b']),
  mk('Word', 1, 'Poner en cursiva', ['Control', 'i']),
  mk('Word', 1, 'Subrayar', ['Control', 'u']),
  mk('Word', 1, 'Guardar', ['Control', 's']),
  mk('Word', 2, 'Centrar el párrafo', ['Control', 'e']),
  mk('Word', 2, 'Alinear a la izquierda', ['Control', 'l']),
  mk('Word', 2, 'Alinear a la derecha', ['Control', 'r']),
  mk('Word', 2, 'Justificar el párrafo', ['Control', 'j']),
  mk('Word', 2, 'Copiar el formato', ['Control', 'Shift', 'c']),
  mk('Word', 3, 'Pegar el formato', ['Control', 'Shift', 'v']),
  mk('Word', 3, 'Aplicar Título 1', ['Control', 'Alt', '1']),
  mk('Word', 3, 'Aplicar Título 2', ['Control', 'Alt', '2']),
  mk('Word', 3, 'Insertar salto de página', ['Control', 'Enter']),
  mk('Word', 3, 'Quitar el formato del texto', ['Control', 'Shift', 'n']),
  mk('Word', 4, 'Aumentar el tamaño de fuente', ['Control', 'Shift', '>']),
  mk('Word', 4, 'Disminuir el tamaño de fuente', ['Control', 'Shift', '<']),

  // ── Excel ──
  mk('Excel', 1, 'Editar la celda activa', ['F2']),
  mk('Excel', 1, 'Copiar', ['Control', 'c']),
  mk('Excel', 1, 'Pegar', ['Control', 'v']),
  mk('Excel', 2, 'Guardar', ['Control', 's']),
  mk('Excel', 2, 'Insertar la fecha de hoy', ['Control', ';']),
  mk('Excel', 2, 'Seleccionar la columna', ['Control', 'Space']),
  mk('Excel', 2, 'Seleccionar la fila', ['Shift', 'Space']),
  mk('Excel', 2, 'Buscar', ['Control', 'f']),
  mk('Excel', 3, 'Ir al borde de los datos (derecha)', ['Control', 'ArrowRight']),
  mk('Excel', 3, 'Seleccionar hasta el borde de los datos', ['Control', 'Shift', 'ArrowRight']),
  mk('Excel', 3, 'Ir a la celda A1', ['Control', 'Home']),
  mk('Excel', 3, 'Abrir formato de celdas', ['Control', '1']),
  mk('Excel', 3, 'Autosuma', ['Alt', '=']),
  mk('Excel', 4, 'Referencia absoluta ($)', ['F4']),
  mk('Excel', 4, 'Insertar filas o columnas', ['Control', 'Shift', '+']),

  // ── Terminal ──
  mk('Terminal', 1, 'Cancelar el comando actual', ['Control', 'c']),
  mk('Terminal', 1, 'Limpiar la pantalla', ['Control', 'l']),
  mk('Terminal', 2, 'Buscar en el historial', ['Control', 'r']),
  mk('Terminal', 2, 'Ir al inicio de la línea', ['Control', 'a']),
  mk('Terminal', 2, 'Ir al final de la línea', ['Control', 'e']),
  mk('Terminal', 3, 'Borrar hasta el inicio de la línea', ['Control', 'u']),
  mk('Terminal', 3, 'Borrar hasta el final de la línea', ['Control', 'k']),
  mk('Terminal', 3, 'Borrar la palabra anterior', ['Control', 'w']),
  mk('Terminal', 3, 'Cerrar la sesión (EOF)', ['Control', 'd']),
  mk('Terminal', 4, 'Suspender el proceso', ['Control', 'z']),
  mk('Terminal', 4, 'Pegar en la terminal', ['Control', 'Shift', 'v']),

  // ── YouTube ──
  mk('YouTube', 1, 'Reproducir o pausar', ['k']),
  mk('YouTube', 1, 'Silenciar', ['m']),
  mk('YouTube', 1, 'Pantalla completa', ['f']),
  mk('YouTube', 2, 'Retroceder 10 segundos', ['j']),
  mk('YouTube', 2, 'Adelantar 10 segundos', ['l']),
  mk('YouTube', 2, 'Activar el modo cine', ['t']),
  mk('YouTube', 2, 'Activar los subtítulos', ['c']),
  mk('YouTube', 3, 'Subir el volumen', ['ArrowUp']),
  mk('YouTube', 3, 'Bajar el volumen', ['ArrowDown']),
  mk('YouTube', 3, 'Retroceder 5 segundos', ['ArrowLeft']),
  mk('YouTube', 3, 'Adelantar 5 segundos', ['ArrowRight']),
  mk('YouTube', 3, 'Abrir el mini reproductor', ['i']),
  mk('YouTube', 4, 'Ir al video siguiente', ['Shift', 'n']),
  mk('YouTube', 4, 'Ir al inicio del video', ['0']),

  // ── Discord ──
  mk('Discord', 1, 'Búsqueda rápida (saltar a)', ['Control', 'k']),
  mk('Discord', 2, 'Silenciar el micrófono', ['Control', 'Shift', 'm']),
  mk('Discord', 2, 'Silenciar el sonido', ['Control', 'Shift', 'd']),
  mk('Discord', 2, 'Abrir la lista de atajos', ['Control', '/']),
  mk('Discord', 2, 'Marcar el canal como leído', ['Escape']),
  mk('Discord', 3, 'Ir al canal anterior', ['Alt', 'ArrowUp']),
  mk('Discord', 3, 'Ir al canal siguiente', ['Alt', 'ArrowDown']),
  mk('Discord', 3, 'Ir al servidor anterior', ['Control', 'Alt', 'ArrowUp']),
  mk('Discord', 3, 'Ir al servidor siguiente', ['Control', 'Alt', 'ArrowDown']),
  mk('Discord', 3, 'Abrir el selector de emojis', ['Control', 'e']),
  mk('Discord', 4, 'Marcar el servidor como leído', ['Shift', 'Escape']),

  // ── Drive ──
  mk('Drive', 1, 'Buscar en Drive', ['/']),
  mk('Drive', 1, 'Seleccionar todos los elementos', ['Control', 'a']),
  mk('Drive', 2, 'Renombrar el elemento', ['n']),
  mk('Drive', 2, 'Ver u ocultar el panel de detalles', ['d']),
  mk('Drive', 2, 'Abrir el menú "Nuevo"', ['c']),
  mk('Drive', 3, 'Mover a la papelera', ['Delete']),
  mk('Drive', 3, 'Copiar', ['Control', 'c']),
  mk('Drive', 3, 'Pegar', ['Control', 'v']),
  mk('Drive', 3, 'Deshacer', ['Control', 'z']),
  mk('Drive', 4, 'Rehacer', ['Control', 'y']),

  // ── Windows ── (modo visual)
  mk('Windows', 1, 'Bloquear la computadora', ['Win', 'l']),
  mk('Windows', 1, 'Mostrar el escritorio', ['Win', 'd']),
  mk('Windows', 1, 'Abrir el explorador de archivos', ['Win', 'e']),
  mk('Windows', 2, 'Cambiar entre aplicaciones', ['Alt', 'Tab']),
  mk('Windows', 2, 'Abrir la configuración', ['Win', 'i']),
  mk('Windows', 2, 'Abrir la búsqueda', ['Win', 's']),
  mk('Windows', 2, 'Minimizar todas las ventanas', ['Win', 'm']),
  mk('Windows', 2, 'Abrir el menú de enlaces rápidos', ['Win', 'x']),
  mk('Windows', 3, 'Abrir el administrador de tareas', ['Control', 'Shift', 'Escape']),
  mk('Windows', 3, 'Captura de pantalla (recorte)', ['Win', 'Shift', 's']),
  mk('Windows', 3, 'Anclar la ventana a la izquierda', ['Win', 'ArrowLeft']),
  mk('Windows', 3, 'Abrir el portapapeles', ['Win', 'v']),
  mk('Windows', 4, 'Crear un escritorio virtual', ['Win', 'Control', 'd']),
  mk('Windows', 4, 'Cerrar el escritorio virtual', ['Win', 'Control', 'F4']),
  mk('Windows', 4, 'Ir al escritorio virtual anterior', ['Win', 'Control', 'ArrowLeft']),
  mk('Windows', 4, 'Ir al escritorio virtual siguiente', ['Win', 'Control', 'ArrowRight']),
];
